version: 2
sources:
    - name: raw
      database: AUTODATA
      schema: RAW_AUTO
      tables:
          - name: CUSTOMER
            columns: 
                - name: CUSTOMER_ID
                  description: "the primary" 
                  tests:
                       - unique
                       - not_null 
          - name: ORDERS
          - name: PRODUCT



    

