sources:
    - name: raw
      database: DB
      schema: RAW_SCH
      tables:
          - name: CUSTOMER
          - name: ORDERS
          - name: PRODUCT

models:
    - name: CUSTOMER
      description: "A starter dbt model"
      columns:
          - name: CUSTOMER_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    

